#
# Config file (consumed by Snakemake) which specifies parameters for the exogenous-driven land transport (toy) model
#


scenario:
  clusters:
    - 37
  planning_horizons: # investment years for myopic and perfect; for overnight, year of cost assumptions can be different and is defined under 'costs'
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050


snapshots:
  start: "2013-01-01"
  end: "2013-12-31"


sector:
  land_transport_electric_share:
    2020: 0.0
    2025: 0.2
    2030: 0.3
    2035: 0.4
    2040: 0.6
    2045: 0.8
    2050: 1.0
  land_transport_ice_share:
    2020: 1.0
    2025: 0.8
    2030: 0.7
    2035: 0.6
    2040: 0.4
    2045: 0.2
    2050: 0.0
  bev_dsm: true #turns on EV battery
  bev_availability: 0.5  #How many cars do smart charging
  bev_energy: 0.05  #average battery size in MWh
  bev_charge_efficiency: 0.9  #BEV (dis-)charging efficiency
  bev_plug_to_wheel_efficiency: 0.2 #kWh/km from EPA https://www.fueleconomy.gov/feg/ for Tesla Model S
  bev_charge_rate: 0.011 #3-phase charger with 11 kW
  bev_avail_max: 0.95
  bev_avail_mean: 0.8
  v2g: true #allows feed-in to grid from EV battery
  transport_internal_combustion_efficiency: 0.3
  MWh_MeOH_per_MWh_H2: 0.8787 # in LHV, source: DECHEMA (2017): Low carbon energy and feedstock for the European chemical industry , pg. 64.
  MWh_MeOH_per_tCO2: 4.0321 # in LHV, source: DECHEMA (2017): Low carbon energy and feedstock for the European chemical industry , pg. 64.
  MWh_MeOH_per_MWh_e: 3.6907 # in LHV, source: DECHEMA (2017): Low carbon energy and feedstock for the European chemical industry , pg. 64.
  solar_cf_correction: 0.788457  # =  >>> 1/1.2683
  marginal_cost_storage: 0.0 #1e-4
  co2_network: false
  electricity_distribution_grid: true
  electricity_distribution_grid_cost_factor: 1.0  #multiplies cost in data/costs.csv
  electricity_grid_connection: true  # only applies to onshore wind and utility PV

