#
# Config file (consumed by Snakemake) which specifies parameters for the exogenous-driven land transport (toy) model
#


scenario:
  clusters:
    - 37
  planning_horizons: # investment years for myopic and perfect; for overnight, year of cost assumptions can be different and is defined under 'costs'
    - 2020
    - 2025
    - 2030
    - 2035
    - 2040
    - 2045
    - 2050


snapshots:
  start: "2013-01-01"
  end: "2013-12-31"


sector:
  land_transport_electric_share:
    2020: 0.0
    2025: 0.2
    2030: 0.3
    2035: 0.4
    2040: 0.6
    2045: 0.8
    2050: 1.0
  land_transport_ice_share:
    2020: 1.0
    2025: 0.8
    2030: 0.7
    2035: 0.6
    2040: 0.4
    2045: 0.2
    2050: 0.0
  bev_dsm: true #turns on EV battery
  bev_availability: 0.5  #How many cars do smart charging
  bev_energy: 0.05  #average battery size in MWh
  bev_charge_efficiency: 0.9  #BEV (dis-)charging efficiency
  bev_charge_rate: 0.011 #3-phase charger with 11 kW
  v2g: true #allows feed-in to grid from EV battery
  transport_internal_combustion_efficiency: 0.3
  icev_consumption_per_unit: 0.05   # arbitrary value
  bev_consumption_per_unit: 0.01   # arbitrary value

