#
# Snakemake file for the exogenous-driven land transport (toy) model
#


configfile: "config.yaml"


RESOURCE_PATH = "../resources/data"
RESULT_PATH = "results"


wildcard_constraints:
    clusters = "[0-9]+m?"


rule all:
    input:
        technology_costs_file = expand(RESOURCE_PATH + "/costs_{planning_horizons}.csv", **config["scenario"]),
        solar_profile_file = RESOURCE_PATH + "/solar_profile_1979_2017.csv",
        transport_data_file = expand(RESOURCE_PATH + "/transport_data_s_{clusters}.csv", **config["scenario"]),
        transport_demand_file = expand(RESOURCE_PATH + "/transport_demand_s_{clusters}.csv", **config["scenario"]),
        availability_profile_file = expand(RESOURCE_PATH + "/avail_profile_s_{clusters}.csv", **config["scenario"]),
        dsm_profile_file = expand(RESOURCE_PATH + "/dsm_profile_s_{clusters}.csv", **config["scenario"])
    output:
        summary_file = RESULT_PATH + "/summary.txt",
        generators_file = expand(RESULT_PATH + "/generators_{planning_horizons}.png", **config["scenario"]),
        stores_file = expand(RESULT_PATH + "/stores_{planning_horizons}.png", **config["scenario"]),
        vehicle_file = RESULT_PATH + "/vehicle.png"
    script:
        "model.py"

