from snakemake.remote.HTTP import RemoteProvider as HTTPRemoteProvider


configfile: "config.yaml"


wildcard_constraints:
    simpl="[a-zA-Z0-9]*",
    clusters="[0-9]+m?"


rule all:
    input:
        expand("results/generators_profile{simpl}_{planning_horizons}.png", **config['scenario']),
	expand('results/elec_s{simpl}_{planning_horizons}.nc',**config['scenario']),
	"results/generators.png",
	"results/vehiclenb.png"
	

rule plots:
    input:
        expand('results/elec_s{simpl}_{planning_horizons}.nc',**config['scenario'])
    output:
        result = "results/generators.png",
        vehiclenb = "results/vehiclenb.png",
        EV_times1 = 'results/EV_timeseries_1.png',
        EV_times2 = 'results/EV_timeseries_2.png',
    script: "scripts/make_plots.py"


rule transport:
    input:
        transport_demand = expand("resources/transport_demand_s{simpl}_{clusters}.csv", **config['scenario']),
        co2_totals_name="resources/co2_totals.csv",
    output:
    	results = "results/generators_profile{simpl}_{planning_horizons}.png",
	network = 'results/elec_s{simpl}_{planning_horizons}.nc'
    script: "scripts/end_transport.py"


# rule to download the tool PyPSATopo
rule retrieve_topo:
    input:
        HTTPRemoteProvider().remote("https://raw.githubusercontent.com/ricnogfer/pypsatopo/v0.5.0/pypsatopo.py", keep_local = True)
    output:
        "scripts/pypsatopo.py"
    run:
        shell("mv {input} scripts/pypsatopo.py")
        shell("chmod u+x scripts/pypsatopo.py")


# rule to generate the topographical representation of a network through PyPSATopo
rule generate_topo:
    input:
        network = expand("results/elec_s{simpl}_{planning_horizons}.nc", **config["scenario"])
    output:
        expand("results/elec_s{simpl}_{planning_horizons}.svg", **config["scenario"])
    shell:
        "scripts/pypsatopo.py -cc -nb -nq {input.network}"


